package com.github.dawid_stolarczyk.magazyn.Common.Enums;

public enum InventoryError {
    ITEM_NOT_FOUND,
    USER_NOT_FOUND,
    PLACEMENT_INVALID,
    NO_REGALS_MATCH,
    INSUFFICIENT_SPACE,
    EXPIRE_AFTER_INVALID,
    RACK_NOT_FOUND,
    WAREHOUSE_NOT_FOUND,
    ASSORTMENT_NOT_FOUND,
    POSITION_OUT_OF_BOUNDS,
    ITEM_TOO_LARGE_FOR_RACK,
    TEMPERATURE_MISMATCH,
    RACK_WEIGHT_LIMIT_EXCEEDED,
    RACK_DOES_NOT_ACCEPT_DANGEROUS_ITEMS,
    POSITION_ALREADY_OCCUPIED,
    INVALID_EXPIRY_DATE,
    WAREHOUSE_ACCESS_DENIED,

    // File validation errors
    FILE_IS_EMPTY,
    MISSING_CONTENT_TYPE,
    INVALID_FILE_TYPE,
    MISSING_FILENAME,
    MISSING_FILE_EXTENSION,
    INVALID_FILE_EXTENSION,
    FILE_TOO_LARGE,
    UNSUPPORTED_IMAGE_TYPE,

    // Barcode generation errors
    BARCODE_GENERATION_FAILED,
    PLACEMENT_BARCODE_GENERATION_FAILED,
    BARCODE_MUST_BE_6_DIGITS
}
