package com.github.dawid_stolarczyk.magazyn.Services.Ratelimiter;

public enum RateLimitOperation {
    AUTH_LOGIN,
    AUTH_REGISTER,
    AUTH_LOGOUT,
    AUTH_FREE,
    FORGOT_PASSWORD,
    EMAIL_VERIFICATION_RESEND,
    TWO_FACTOR_FREE,
    TWO_FACTOR_VERIFY,
    TWO_FACTOR_STRICT,
    USER_ACTION_FREE,
    USER_ACTION_STRICT,
    WEBAUTH_ASSERTION,
    WEBAUTH_REGISTRATION,
    INVENTORY_READ,
    INVENTORY_WRITE,
    BACKUP_READ,
    BACKUP_WRITE,
    REPORT_GENERATE,
    TELEMETRY_WRITE
}
