import type { ItemInstance, ItemStats } from "./items/types"
import type { Notification, User } from "./types"

const MOCK_ITEMS: ItemInstance[] = [
  {
    id: "item-0",
    definitionId: "def-1",
    definition: {
      id: "def-1",
      name: "Produkt 1",
      category: "Kategoria-1",
      description: "Opis produktu 1",
      defaultMinTemp: 10,
      defaultMaxTemp: 30,
      defaultWeight: 2.5,
      shelfLife: 730,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-1",
    addedDate: new Date("2024-06-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 2.5,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 0 },
    currentTemp: 20,
    comment: "Komentarz1",
  },
  {
    id: "item-1",
    definitionId: "def-2",
    definition: {
      id: "def-2",
      name: "Produkt 2",
      category: "Kategoria-2",
      description: "Opis produktu 2",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 5.0,
      shelfLife: 1095,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-2",
    addedDate: new Date("2024-06-15"),
    expiryDate: new Date("2026-06-30"),
    weight: 5.0,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 1 },
    currentTemp: 18,
    comment: "Komentarz2",
  },
  {
    id: "item-2",
    definitionId: "def-3",
    definition: {
      id: "def-3",
      name: "Produkt 3",
      category: "Kategoria-3",
      description: "Opis produktu 3",
      defaultMinTemp: 5,
      defaultMaxTemp: 35,
      defaultWeight: 4.5,
      shelfLife: 1825,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-3",
    addedDate: new Date("2024-07-01"),
    expiryDate: new Date("2030-12-31"),
    weight: 4.5,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 2 },
    currentTemp: 22,
    comment: "",
  },
  {
    id: "item-4",
    definitionId: "def-5",
    definition: {
      id: "def-5",
      name: "Produkt 5",
      category: "Kategoria-4",
      description: "Opis produktu 5",
      defaultMinTemp: 5,
      defaultMaxTemp: 30,
      defaultWeight: 30.0,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-5",
    addedDate: new Date("2024-08-01"),
    expiryDate: new Date("2025-06-30"),
    weight: 30.0,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 4 },
    currentTemp: 19,
    comment: "Komentarz5",
  },
  {
    id: "item-5",
    definitionId: "def-6",
    definition: {
      id: "def-6",
      name: "Produkt 6",
      category: "Kategoria-2",
      description: "Opis produktu 6",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 18,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-6",
    addedDate: new Date("2024-09-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 18,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 5 },
    currentTemp: 20,
    comment: "",
  },
  {
    id: "item-9",
    definitionId: "def-10",
    definition: {
      id: "def-10",
      name: "Produkt 10",
      category: "Kategoria-1",
      description: "Opis produktu 10",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 12,
      shelfLife: 730,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-10",
    addedDate: new Date("2024-10-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 12,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 9 },
    currentTemp: 21,
    comment: "",
  },
  {
    id: "item-12",
    definitionId: "def-13",
    definition: {
      id: "def-13",
      name: "Produkt 13",
      category: "Kategoria-3",
      description: "Opis produktu 13",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 27,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-13",
    addedDate: new Date("2024-11-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 27,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 1, col: 0 },
    currentTemp: 19,
    comment: "",
  },
  {
    id: "item-13",
    definitionId: "def-14",
    definition: {
      id: "def-14",
      name: "Produkt 14",
      category: "Kategoria-2",
      description: "Opis produktu 14",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 45,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-14",
    addedDate: new Date("2024-11-15"),
    expiryDate: new Date("2025-12-31"),
    weight: 45,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 1, col: 1 },
    currentTemp: 20,
    comment: "",
  },
  {
    id: "item-15",
    definitionId: "def-16",
    definition: {
      id: "def-16",
      name: "Produkt 16",
      category: "Kategoria-4",
      description: "Opis produktu 16",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 24,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-16",
    addedDate: new Date("2024-12-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 24,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 1, col: 3 },
    currentTemp: 21,
    comment: "",
  },
  {
    id: "item-a2-1",
    definitionId: "def-20",
    definition: {
      id: "def-20",
      name: "Produkt A2-1",
      category: "Kategoria-1",
      description: "Opis produktu A2-1",
      defaultMinTemp: 10,
      defaultMaxTemp: 30,
      defaultWeight: 3.5,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A2-01",
    addedDate: new Date("2024-06-01"),
    expiryDate: new Date("2025-06-01"),
    weight: 3.5,
    warehouseId: "A2",
    warehouseName: "Magazyn A2",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 0 },
    currentTemp: 20,
    comment: "Produkt z magazynu A2",
  },
  {
    id: "item-a2-2",
    definitionId: "def-21",
    definition: {
      id: "def-21",
      name: "Produkt A2-2",
      category: "Kategoria-2",
      description: "Opis produktu A2-2",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 8.0,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A2-02",
    addedDate: new Date("2024-07-01"),
    expiryDate: new Date("2026-07-01"),
    weight: 8.0,
    warehouseId: "A2",
    warehouseName: "Magazyn A2",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 1 },
    currentTemp: 18,
    comment: "Produkt niebezpieczny z magazynu A2",
  },
  {
    id: "item-a3-1",
    definitionId: "def-30",
    definition: {
      id: "def-30",
      name: "Produkt A3-1",
      category: "Kategoria-3",
      description: "Opis produktu A3-1",
      defaultMinTemp: 5,
      defaultMaxTemp: 35,
      defaultWeight: 6.0,
      shelfLife: 1095,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A3-01",
    addedDate: new Date("2024-05-01"),
    expiryDate: new Date("2027-05-01"),
    weight: 6.0,
    warehouseId: "A3",
    warehouseName: "Magazyn A3",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 0 },
    currentTemp: 22,
    comment: "Produkt z magazynu A3",
  },
  {
    id: "item-a3-2",
    definitionId: "def-31",
    definition: {
      id: "def-31",
      name: "Produkt A3-2",
      category: "Kategoria-4",
      description: "Opis produktu A3-2",
      defaultMinTemp: 10,
      defaultMaxTemp: 30,
      defaultWeight: 15.0,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A3-02",
    addedDate: new Date("2024-08-01"),
    expiryDate: new Date("2025-08-01"),
    weight: 15.0,
    warehouseId: "A3",
    warehouseName: "Magazyn A3",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 1 },
    currentTemp: 20,
    comment: "Kolejny produkt z magazynu A3",
  },
  {
    id: "item-a3-3",
    definitionId: "def-32",
    definition: {
      id: "def-32",
      name: "Produkt A3-3",
      category: "Kategoria-1",
      description: "Opis produktu A3-3",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 10.0,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A3-03",
    addedDate: new Date("2024-09-01"),
    expiryDate: new Date("2026-09-01"),
    weight: 10.0,
    warehouseId: "A3",
    warehouseName: "Magazyn A3",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 2 },
    currentTemp: 19,
    comment: "Niebezpieczny produkt z magazynu A3",
  },
]

const MOCK_ITEM_STATS: ItemStats[] = [
  {
    definitionId: "def-1",
    definition: {
      id: "def-1",
      name: "Produkt 1",
      category: "Kategoria-1",
      description: "Opis produktu 1",
      defaultMinTemp: 10,
      defaultMaxTemp: 30,
      defaultWeight: 2.5,
      shelfLife: 730,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 2.5,
  },
  {
    definitionId: "def-2",
    definition: {
      id: "def-2",
      name: "Produkt 2",
      category: "Kategoria-2",
      description: "Opis produktu 2",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 5.0,
      shelfLife: 1095,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2026-06-30"),
    daysUntilExpiry: 549,
    weight: 5.0,
  },
  {
    definitionId: "def-3",
    definition: {
      id: "def-3",
      name: "Produkt 3",
      category: "Kategoria-3",
      description: "Opis produktu 3",
      defaultMinTemp: 5,
      defaultMaxTemp: 35,
      defaultWeight: 4.5,
      shelfLife: 1825,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2030-12-31"),
    daysUntilExpiry: 1829,
    weight: 4.5,
  },
  {
    definitionId: "def-5",
    definition: {
      id: "def-5",
      name: "Produkt 5",
      category: "Kategoria-4",
      description: "Opis produktu 5",
      defaultMinTemp: 5,
      defaultMaxTemp: 30,
      defaultWeight: 30.0,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-06-30"),
    daysUntilExpiry: 184,
    weight: 30.0,
  },
  {
    definitionId: "def-6",
    definition: {
      id: "def-6",
      name: "Produkt 6",
      category: "Kategoria-2",
      description: "Opis produktu 6",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 18,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 18,
  },
  {
    definitionId: "def-10",
    definition: {
      id: "def-10",
      name: "Produkt 10",
      category: "Kategoria-1",
      description: "Opis produktu 10",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 12,
      shelfLife: 730,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 12,
  },
  {
    definitionId: "def-13",
    definition: {
      id: "def-13",
      name: "Produkt 13",
      category: "Kategoria-3",
      description: "Opis produktu 13",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 27,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 27,
  },
  {
    definitionId: "def-14",
    definition: {
      id: "def-14",
      name: "Produkt 14",
      category: "Kategoria-2",
      description: "Opis produktu 14",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 45,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 45,
  },
  {
    definitionId: "def-16",
    definition: {
      id: "def-16",
      name: "Produkt 16",
      category: "Kategoria-4",
      description: "Opis produktu 16",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 24,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 24,
  },
]

const MOCK_ITEM_DEFINITIONS = MOCK_ITEM_STATS.map((stat) => stat.definition)

const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    title: "Nieautoryzowane pobranie",
    description:
      "Wykryto spadek wagi na regale R-001 bez zarejestrowanej operacji",
    type: "UNAUTHORIZED_REMOVAL",
    severity: "CRITICAL",
    warehouseId: "wh-1",
    rackId: "rack-001",
    metadata: { weightDelta: -2.5, previousWeight: 450, currentWeight: 447.5 },
    date: "2h temu",
    read: false,
    createdAt: new Date("2024-01-15T09:30:00Z"),
  },
  {
    id: "2",
    title: "Przekroczenie wagi regału",
    description: "Regał R-002 przekroczył maksymalną wagę o 15kg",
    type: "RACK_OVERWEIGHT",
    severity: "WARNING",
    warehouseId: "wh-1",
    rackId: "rack-002",
    metadata: { maxWeight: 500, currentWeight: 515 },
    date: "1h temu",
    read: false,
    createdAt: new Date("2024-01-15T10:15:00Z"),
  },
  {
    id: "4",
    title: "Produkt przeterminowany",
    description: "Produkt 'Mleko 1L' na regale R-001 przekroczył datę ważności",
    type: "ITEM_EXPIRED",
    severity: "INFO",
    warehouseId: "wh-1",
    rackId: "rack-001",
    itemId: "item-123",
    metadata: { expiryDate: "2024-01-14", productName: "Mleko 1L" },
    date: "1h temu",
    read: true,
    createdAt: new Date("2024-01-15T10:45:00Z"),
  },
  {
    id: "5",
    title: "Nieautoryzowane pobranie",
    description:
      "Wykryto spadek wagi na regale R-005 bez zarejestrowanej operacji",
    type: "UNAUTHORIZED_REMOVAL",
    severity: "CRITICAL",
    warehouseId: "wh-2",
    rackId: "rack-005",
    metadata: { weightDelta: -5.0, previousWeight: 320, currentWeight: 315 },
    date: "1h temu",
    read: false,
    createdAt: new Date("2024-01-15T10:30:00Z"),
  },
  {
    id: "6",
    title: "Naruszenie temperatury",
    description: "Temperatura na regale R-004 spadła poniżej minimum (2°C)",
    type: "TEMPERATURE_VIOLATION",
    severity: "WARNING",
    warehouseId: "wh-1",
    rackId: "rack-004",
    metadata: { minTemp: 4, currentTemp: 2, maxTemp: 8 },
    date: "30min temu",
    read: false,
    createdAt: new Date("2024-01-15T11:00:00Z"),
  },
]

const MOCK_USERS: User[] = [
  {
    id: "u-1001",
    username: "john_doe",
    email: "john.doe@example.com",
    role: "ADMIN",
    team: "Operacje",
    status: "ACTIVE",
  },
  {
    id: "u-1002",
    username: "jane_smith",
    email: "jane.smith@example.com",
    role: "USER",
    team: "Magazyn",
    status: "ACTIVE",
  },
  {
    id: "u-1003",
    username: "pawel",
    email: "pawel@example.com",
    role: "USER",
    team: "Magazyn",
    status: "INACTIVE",
  },
  {
    id: "u-1004",
    username: "kasia",
    email: "kasia@example.com",
    role: "ADMIN",
    team: "Operacje",
    status: "ACTIVE",
  },
  {
    id: "u-1005",
    username: "adam",
    email: "adam@example.com",
    role: "USER",
    team: "Wysyłka",
    status: "INACTIVE",
  },
  {
    id: "u-1006",
    username: "ola",
    email: "ola@example.com",
    role: "USER",
    team: "Przyjęcia",
    status: "ACTIVE",
  },
  {
    id: "u-1007",
    username: "krzysiek",
    email: "krzysiek@example.com",
    role: "USER",
    team: "Magazyn",
    status: "ACTIVE",
  },
  {
    id: "u-1008",
    username: "magda",
    email: "magda@example.com",
    role: "ADMIN",
    team: "Kontrola jakości",
    status: "ACTIVE",
  },
  {
    id: "u-1009",
    username: "dominik",
    email: "dominik@example.com",
    role: "USER",
    team: "Wysyłka",
    status: "INACTIVE",
  },
  {
    id: "u-1010",
    username: "user-10",
    email: "user-10@example.com",
    role: "USER",
    team: "Przyjęcia",
    status: "ACTIVE",
  },
  {
    id: "u-1013",
    username: "user-13",
    email: "user-13@example.com",
    role: "USER",
    team: "Magazyn",
    status: "ACTIVE",
  },
  {
    id: "u-1011",
    username: "user-11",
    email: "user-11@example.com",
    role: "USER",
    team: "Operacje",
    status: "ACTIVE",
  },
  {
    id: "u-1012",
    username: "user-12",
    email: "user-12@example.com",
    role: "USER",
    team: "Kontrola jakości",
    status: "ACTIVE",
  },
]

export {
  MOCK_ITEMS,
  MOCK_ITEM_STATS,
  MOCK_ITEM_DEFINITIONS,
  MOCK_NOTIFICATIONS,
  MOCK_USERS,
}
