import type { ItemInstance, ItemStats } from "./items/types"
import type { Rack } from "./types"

const MOCK_RACKS: Rack[] = [
  {
    id: "rack-0",
    name: "Regał A",
    rows: 10,
    cols: 12,
    minTemp: 15,
    maxTemp: 25,
    maxWeight: 1000,
    currentWeight: 450,
    occupancy: 70,
    items: [
      {
        id: "item-0",
        name: "Produkt 1",
        qrCode: "QR-1",
        expiryDate: new Date("2025-12-31"),
        weight: 2.5,
        dimensions: { x: 350, y: 235, z: 18 },
        minTemp: 10,
        maxTemp: 30,
        comment: "Komentarz1",
        isDangerous: false,
        imageUrl: null,
      },
      {
        id: "item-1",
        name: "Produkt 2",
        qrCode: "QR-2",
        expiryDate: new Date("2026-06-30"),
        weight: 5.0,
        dimensions: { x: 150, y: 150, z: 300 },
        minTemp: 15,
        maxTemp: 25,
        comment: "Komentarz2",
        isDangerous: true,
        imageUrl: null,
      },
      {
        id: "item-2",
        name: "Produkt 3",
        qrCode: "QR-3",
        expiryDate: new Date("2030-12-31"),
        weight: 4.5,
        dimensions: { x: 610, y: 450, z: 180 },
        minTemp: 5,
        maxTemp: 35,
        comment: "",
        isDangerous: false,
        imageUrl: null,
      },
      null,
      {
        id: "item-4",
        name: "Produkt 5",
        qrCode: "QR-5",
        expiryDate: new Date("2025-06-30"),
        weight: 30.0,
        dimensions: { x: 400, y: 600, z: 120 },
        minTemp: 5,
        maxTemp: 30,
        comment: "Komentarz5",
        isDangerous: false,
        imageUrl: null,
      },
      {
        id: "item-5",
        name: "Produkt 6",
        qrCode: "QR-6",
        expiryDate: new Date("2025-12-31"),
        weight: 18,
        dimensions: { x: 100, y: 100, z: 100 },
        minTemp: 15,
        maxTemp: 25,
        comment: "",
        isDangerous: true,
        imageUrl: null,
      },
      null,
      null,
      null,
      {
        id: "item-9",
        name: "Produkt 10",
        qrCode: "QR-10",
        expiryDate: new Date("2025-12-31"),
        weight: 12,
        dimensions: { x: 100, y: 100, z: 100 },
        minTemp: 15,
        maxTemp: 25,
        comment: "",
        isDangerous: false,
        imageUrl: null,
      },
      null,
      null,
      {
        id: "item-12",
        name: "Produkt 13",
        qrCode: "QR-13",
        expiryDate: new Date("2025-12-31"),
        weight: 27,
        dimensions: { x: 100, y: 100, z: 100 },
        minTemp: 15,
        maxTemp: 25,
        comment: "",
        isDangerous: false,
        imageUrl: null,
      },
      {
        id: "item-13",
        name: "Produkt 14",
        qrCode: "QR-14",
        expiryDate: new Date("2025-12-31"),
        weight: 45,
        dimensions: { x: 100, y: 100, z: 100 },
        minTemp: 15,
        maxTemp: 25,
        comment: "",
        isDangerous: true,
        imageUrl: null,
      },
      null,
      {
        id: "item-15",
        name: "Produkt 16",
        qrCode: "QR-16",
        expiryDate: new Date("2025-12-31"),
        weight: 24,
        dimensions: { x: 100, y: 100, z: 100 },
        minTemp: 15,
        maxTemp: 25,
        comment: "",
        isDangerous: false,
        imageUrl: null,
      },
    ],
  },
  {
    id: "rack-1",
    name: "Regał B",
    rows: 100,
    cols: 100,
    minTemp: 10,
    maxTemp: 20,
    maxWeight: 1000,
    currentWeight: 620,
    occupancy: 40,
    items: [
      {
        id: "item-b0",
        name: "Produkt B1",
        qrCode: "QR-B01",
        expiryDate: new Date("2025-12-31"),
        weight: 20,
        dimensions: { x: 100, y: 100, z: 100 },
        minTemp: 10,
        maxTemp: 20,
        comment: "",
        isDangerous: false,
        imageUrl: null,
      },
      null,
      null,
      null,
      null,
      null,
      {
        id: "item-b6",
        name: "Produkt B7",
        qrCode: "QR-B07",
        expiryDate: new Date("2025-12-31"),
        weight: 33,
        dimensions: { x: 100, y: 100, z: 100 },
        minTemp: 10,
        maxTemp: 20,
        comment: "",
        isDangerous: false,
        imageUrl: null,
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "rack-2",
    name: "Regał C",
    rows: 4,
    cols: 5,
    minTemp: 5,
    maxTemp: 15,
    maxWeight: 1000,
    currentWeight: 280,
    occupancy: 20,
    items: [
      {
        id: "item-c0",
        name: "Produkt C1",
        qrCode: "QR-C01",
        expiryDate: new Date("2025-12-31"),
        weight: 40,
        dimensions: { x: 100, y: 100, z: 100 },
        minTemp: 5,
        maxTemp: 15,
        comment: "",
        isDangerous: false,
        imageUrl: null,
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      {
        id: "item-c10",
        name: "Produkt C11",
        qrCode: "QR-C11",
        expiryDate: new Date("2025-12-31"),
        weight: 22,
        dimensions: { x: 100, y: 100, z: 100 },
        minTemp: 5,
        maxTemp: 15,
        comment: "",
        isDangerous: true,
        imageUrl: null,
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
]

const MOCK_WAREHOUSES = [
  {
    id: "A1",
    name: "Magazyn A1",
    racks: MOCK_RACKS.slice(0, 5),
  },
  {
    id: "A2",
    name: "Magazyn A2",
    racks: MOCK_RACKS.slice(0, 1),
  },
  {
    id: "A3",
    name: "Magazyn A3",
    racks: MOCK_RACKS.slice(0, 8),
  },
]

const MOCK_ITEMS: ItemInstance[] = [
  {
    id: "item-0",
    definitionId: "def-1",
    definition: {
      id: "def-1",
      name: "Produkt 1",
      category: "Kategoria-1",
      description: "Opis produktu 1",
      defaultMinTemp: 10,
      defaultMaxTemp: 30,
      defaultWeight: 2.5,
      shelfLife: 730,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-1",
    addedDate: new Date("2024-06-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 2.5,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 0 },
    currentTemp: 20,
    comment: "Komentarz1",
  },
  {
    id: "item-1",
    definitionId: "def-2",
    definition: {
      id: "def-2",
      name: "Produkt 2",
      category: "Kategoria-2",
      description: "Opis produktu 2",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 5.0,
      shelfLife: 1095,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-2",
    addedDate: new Date("2024-06-15"),
    expiryDate: new Date("2026-06-30"),
    weight: 5.0,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 1 },
    currentTemp: 18,
    comment: "Komentarz2",
  },
  {
    id: "item-2",
    definitionId: "def-3",
    definition: {
      id: "def-3",
      name: "Produkt 3",
      category: "Kategoria-3",
      description: "Opis produktu 3",
      defaultMinTemp: 5,
      defaultMaxTemp: 35,
      defaultWeight: 4.5,
      shelfLife: 1825,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-3",
    addedDate: new Date("2024-07-01"),
    expiryDate: new Date("2030-12-31"),
    weight: 4.5,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 2 },
    currentTemp: 22,
    comment: "",
  },
  {
    id: "item-4",
    definitionId: "def-5",
    definition: {
      id: "def-5",
      name: "Produkt 5",
      category: "Kategoria-4",
      description: "Opis produktu 5",
      defaultMinTemp: 5,
      defaultMaxTemp: 30,
      defaultWeight: 30.0,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-5",
    addedDate: new Date("2024-08-01"),
    expiryDate: new Date("2025-06-30"),
    weight: 30.0,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 4 },
    currentTemp: 19,
    comment: "Komentarz5",
  },
  {
    id: "item-5",
    definitionId: "def-6",
    definition: {
      id: "def-6",
      name: "Produkt 6",
      category: "Kategoria-2",
      description: "Opis produktu 6",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 18,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-6",
    addedDate: new Date("2024-09-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 18,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 5 },
    currentTemp: 20,
    comment: "",
  },
  {
    id: "item-9",
    definitionId: "def-10",
    definition: {
      id: "def-10",
      name: "Produkt 10",
      category: "Kategoria-1",
      description: "Opis produktu 10",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 12,
      shelfLife: 730,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-10",
    addedDate: new Date("2024-10-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 12,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 9 },
    currentTemp: 21,
    comment: "",
  },
  {
    id: "item-12",
    definitionId: "def-13",
    definition: {
      id: "def-13",
      name: "Produkt 13",
      category: "Kategoria-3",
      description: "Opis produktu 13",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 27,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-13",
    addedDate: new Date("2024-11-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 27,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 1, col: 0 },
    currentTemp: 19,
    comment: "",
  },
  {
    id: "item-13",
    definitionId: "def-14",
    definition: {
      id: "def-14",
      name: "Produkt 14",
      category: "Kategoria-2",
      description: "Opis produktu 14",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 45,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-14",
    addedDate: new Date("2024-11-15"),
    expiryDate: new Date("2025-12-31"),
    weight: 45,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 1, col: 1 },
    currentTemp: 20,
    comment: "",
  },
  {
    id: "item-15",
    definitionId: "def-16",
    definition: {
      id: "def-16",
      name: "Produkt 16",
      category: "Kategoria-4",
      description: "Opis produktu 16",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 24,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-16",
    addedDate: new Date("2024-12-01"),
    expiryDate: new Date("2025-12-31"),
    weight: 24,
    warehouseId: "A1",
    warehouseName: "Magazyn A1",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 1, col: 3 },
    currentTemp: 21,
    comment: "",
  },
  {
    id: "item-a2-1",
    definitionId: "def-20",
    definition: {
      id: "def-20",
      name: "Produkt A2-1",
      category: "Kategoria-1",
      description: "Opis produktu A2-1",
      defaultMinTemp: 10,
      defaultMaxTemp: 30,
      defaultWeight: 3.5,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A2-01",
    addedDate: new Date("2024-06-01"),
    expiryDate: new Date("2025-06-01"),
    weight: 3.5,
    warehouseId: "A2",
    warehouseName: "Magazyn A2",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 0 },
    currentTemp: 20,
    comment: "Produkt z magazynu A2",
  },
  {
    id: "item-a2-2",
    definitionId: "def-21",
    definition: {
      id: "def-21",
      name: "Produkt A2-2",
      category: "Kategoria-2",
      description: "Opis produktu A2-2",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 8.0,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A2-02",
    addedDate: new Date("2024-07-01"),
    expiryDate: new Date("2026-07-01"),
    weight: 8.0,
    warehouseId: "A2",
    warehouseName: "Magazyn A2",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 1 },
    currentTemp: 18,
    comment: "Produkt niebezpieczny z magazynu A2",
  },
  {
    id: "item-a3-1",
    definitionId: "def-30",
    definition: {
      id: "def-30",
      name: "Produkt A3-1",
      category: "Kategoria-3",
      description: "Opis produktu A3-1",
      defaultMinTemp: 5,
      defaultMaxTemp: 35,
      defaultWeight: 6.0,
      shelfLife: 1095,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A3-01",
    addedDate: new Date("2024-05-01"),
    expiryDate: new Date("2027-05-01"),
    weight: 6.0,
    warehouseId: "A3",
    warehouseName: "Magazyn A3",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 0 },
    currentTemp: 22,
    comment: "Produkt z magazynu A3",
  },
  {
    id: "item-a3-2",
    definitionId: "def-31",
    definition: {
      id: "def-31",
      name: "Produkt A3-2",
      category: "Kategoria-4",
      description: "Opis produktu A3-2",
      defaultMinTemp: 10,
      defaultMaxTemp: 30,
      defaultWeight: 15.0,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A3-02",
    addedDate: new Date("2024-08-01"),
    expiryDate: new Date("2025-08-01"),
    weight: 15.0,
    warehouseId: "A3",
    warehouseName: "Magazyn A3",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 1 },
    currentTemp: 20,
    comment: "Kolejny produkt z magazynu A3",
  },
  {
    id: "item-a3-3",
    definitionId: "def-32",
    definition: {
      id: "def-32",
      name: "Produkt A3-3",
      category: "Kategoria-1",
      description: "Opis produktu A3-3",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 10.0,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    qrCode: "QR-A3-03",
    addedDate: new Date("2024-09-01"),
    expiryDate: new Date("2026-09-01"),
    weight: 10.0,
    warehouseId: "A3",
    warehouseName: "Magazyn A3",
    rackId: "rack-0",
    rackName: "Regał A",
    position: { row: 0, col: 2 },
    currentTemp: 19,
    comment: "Niebezpieczny produkt z magazynu A3",
  },
]

const MOCK_ITEM_STATS: ItemStats[] = [
  {
    definitionId: "def-1",
    definition: {
      id: "def-1",
      name: "Produkt 1",
      category: "Kategoria-1",
      description: "Opis produktu 1",
      defaultMinTemp: 10,
      defaultMaxTemp: 30,
      defaultWeight: 2.5,
      shelfLife: 730,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 2.5,
  },
  {
    definitionId: "def-2",
    definition: {
      id: "def-2",
      name: "Produkt 2",
      category: "Kategoria-2",
      description: "Opis produktu 2",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 5.0,
      shelfLife: 1095,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2026-06-30"),
    daysUntilExpiry: 549,
    weight: 5.0,
  },
  {
    definitionId: "def-3",
    definition: {
      id: "def-3",
      name: "Produkt 3",
      category: "Kategoria-3",
      description: "Opis produktu 3",
      defaultMinTemp: 5,
      defaultMaxTemp: 35,
      defaultWeight: 4.5,
      shelfLife: 1825,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2030-12-31"),
    daysUntilExpiry: 1829,
    weight: 4.5,
  },
  {
    definitionId: "def-5",
    definition: {
      id: "def-5",
      name: "Produkt 5",
      category: "Kategoria-4",
      description: "Opis produktu 5",
      defaultMinTemp: 5,
      defaultMaxTemp: 30,
      defaultWeight: 30.0,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-06-30"),
    daysUntilExpiry: 184,
    weight: 30.0,
  },
  {
    definitionId: "def-6",
    definition: {
      id: "def-6",
      name: "Produkt 6",
      category: "Kategoria-2",
      description: "Opis produktu 6",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 18,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 18,
  },
  {
    definitionId: "def-10",
    definition: {
      id: "def-10",
      name: "Produkt 10",
      category: "Kategoria-1",
      description: "Opis produktu 10",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 12,
      shelfLife: 730,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 12,
  },
  {
    definitionId: "def-13",
    definition: {
      id: "def-13",
      name: "Produkt 13",
      category: "Kategoria-3",
      description: "Opis produktu 13",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 27,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 27,
  },
  {
    definitionId: "def-14",
    definition: {
      id: "def-14",
      name: "Produkt 14",
      category: "Kategoria-2",
      description: "Opis produktu 14",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 45,
      shelfLife: 730,
      isDangerous: true,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 45,
  },
  {
    definitionId: "def-16",
    definition: {
      id: "def-16",
      name: "Produkt 16",
      category: "Kategoria-4",
      description: "Opis produktu 16",
      defaultMinTemp: 15,
      defaultMaxTemp: 25,
      defaultWeight: 24,
      shelfLife: 365,
      isDangerous: false,
      imageUrl: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    totalQuantity: 1,
    warehouseQuantities: { A1: 1 },
    nearestExpiryDate: new Date("2025-12-31"),
    daysUntilExpiry: 368,
    weight: 24,
  },
]

const MOCK_ITEM_DEFINITIONS = MOCK_ITEM_STATS.map((stat) => stat.definition)

export {
  MOCK_WAREHOUSES,
  MOCK_RACKS,
  MOCK_ITEMS,
  MOCK_ITEM_STATS,
  MOCK_ITEM_DEFINITIONS,
}
