// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "breadcrumbs": {
    "dashboard": "Panel",
    "settings": "Ustawienia",
    "profile": "Profil",
    "notifications": "Powiadomienia"
  }
};
export default messages;